#!/bin/bash
#include <stdio.h>
int main()
{


$CFILE *sourceF;
$c *destinationF;
char fileValue;
sourceF = fopen($CFILE, "r");
destinationF = fopen($c, "w");

fileValue =fgetc(sourceF);

fputc(fileValue, $c);

fclose(ftpr1);
fclose(ftpr2);

return 0;
}
